name: Generate SDK

on:
  repository_dispatch:
    types: [regenerate-sdk]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.BUILD_GITHUB_TOKEN }}

      - uses: rixlhq/openapi/.github/actions/setup-kiota@main

      - name: Generate
        run: ./gen.sh

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "feat(sdk): regenerate based on latest OpenAPI spec"
          file_pattern: "sdk/*"
